### ISSUE TITLE
Can not build PowerMonkey.efi

### ISSUE THREAD

**Issue by ghost** [awyl/Build-PowerMonkey#6]
Hi,

I'm newbie, I did instruction but these errors displayed. How can I fix it?

NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx86\x64\cl.exe"' : return code '0x2'
Stop.
C:\Users\VM\Build-PowerMonkey\python\Lib\site-packages\edk2basetools\build\build.py:646: DeprecationWarning: isSet() is deprecated, use is_set() instead
  if not BuildTask._ErrorFlag.isSet():

build.py...
 : error 7000: Failed to execute command
        C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx86\x86\nmake.exe /nologo tbuild [c:\users\vm\build-powermonkey\edk2\Build\MdeModule\RELEASE_VS2019\X64\MdeModulePkg\Application\PowerMonkeyApp\PowerMonkey]
C:\Users\VM\Build-PowerMonkey\python\Lib\site-packages\edk2basetools\build\build.py:655: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  (threading.currentThread().getName(), Command, WorkingDir)
C:\Users\VM\Build-PowerMonkey\python\Lib\site-packages\edk2basetools\build\build.py:655: DeprecationWarning: getName() is deprecated, get the name attribute instead
  (threading.currentThread().getName(), Command, WorkingDir)

build.py...
 : error F002: Failed to build module
        c:\users\vm\build-powermonkey\edk2\MdeModulePkg\Application\PowerMonkeyApp\PowerMonkey.inf [X64, VS2019, RELEASE]

- Failed -
Build end time: 16:04:43, Feb.20 2022
Build total time: 00:00:05

The system cannot find the file specified.

**Comment by awyl** [comment]
I just tested again.

Opened `Developer Command Prompt VS2022`
```
git clone https://github.com/awyl/Build-PowerMonkey.git
setup.bat
build.bat
```

I am not sure how you got that error.  It is probably your dev environment.

**Comment by ghost** [comment]
> I just tested again.
> 
> Opened `Developer Command Prompt VS2022`
> 
> ```
> git clone https://github.com/awyl/Build-PowerMonkey.git
> setup.bat
> build.bat
> ```
> 
> I am not sure how you got that error. It is probably your dev environment.

Hi,
I tried it and it was successful.
Thank you.

**Comment by pa1kia** [comment]
I'm encountering these exact same errors. I've tried running the developer command prompt in both x86 & amd64 architectures, as other issues seemed to find luck with x86, yet the build process fails with these same errors each time. Running Visual Studio 2022 v17.8.3
